### PR TITLE
Inline rejecting states and some rewrites

### PR DESCRIPTION
**Pull request by QuarticCat**

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
@QuarticCat With this PR, our performance gets on top of `serde`.
```
throughput/pag          time:   [633.06 µs 634.92 µs 637.98 µs]                           
                        thrpt:  [624.13 MiB/s 627.13 MiB/s 628.97 MiB/s]
throughput/csv          time:   [531.67 µs 531.88 µs 532.11 µs]                           
                        thrpt:  [748.30 MiB/s 748.62 MiB/s 748.93 MiB/s]
throughput/pest         time:   [4.1875 ms 4.3758 ms 4.5858 ms]                             
                        thrpt:  [86.830 MiB/s 90.997 MiB/s 95.087 MiB/s]

Gnuplot not found, using plotters backend
random-json/pag-json    time:   [24.256 ns 24.359 ns 24.485 ns]                                  
                        thrpt:  [778.98 MiB/s 783.01 MiB/s 786.35 MiB/s]
random-json/serde-json  time:   [24.902 ns 25.065 ns 25.249 ns]                                    
                        thrpt:  [755.42 MiB/s 760.97 MiB/s 765.93 MiB/s]
random-json/pest-json   time:   [221.93 ns 222.86 ns 224.09 ns]                                  
                        thrpt:  [85.114 MiB/s 85.585 MiB/s 85.942 MiB/s]

Benchmarking twitter-json/pag-json: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.7s, enable flat sampling, or reduce sample count to 60.
twitter-json/pag-json   time:   [1.1259 ms 1.1270 ms 1.1284 ms]                                   
                        thrpt:  [648.18 MiB/s 648.97 MiB/s 649.61 MiB/s]
                 change:
                        time:   [-16.245% -16.033% -15.821%] (p = 0.00 < 0.05)
                        thrpt:  [+18.795% +19.094% +19.396%]
                        Performance has improved.
Benchmarking twitter-json/serde-json: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.2s, enable flat sampling, or reduce sample count to 60.
twitter-json/serde-json time:   [1.2188 ms 1.2193 ms 1.2197 ms]                                     
                        thrpt:  [599.63 MiB/s 599.86 MiB/s 600.07 MiB/s]
                 change:
                        time:   [-0.1022% -0.0155% +0.0778%] (p = 0.75 > 0.05)
                        thrpt:  [-0.0777% +0.0155% +0.1023%]
                        No change in performance detected.
twitter-json/pest-json  time:   [5.2474 ms 5.2516 ms 5.2560 ms]                                    
                        thrpt:  [139.15 MiB/s 139.27 MiB/s 139.38 MiB/s]
                 change:
                        time:   [-0.4432% -0.3254% -0.2071%] (p = 0.00 < 0.05)
                        thrpt:  [+0.2075% +0.3264% +0.4452%]
                        Change within noise threshold.
```

**Review by SchrodingerZhu — APPROVED** [review]
LGTM. Nice job!

**Review by SchrodingerZhu — APPROVED** [review]
LGTM. Nice job!

**Comment by anqurvanillapy** [comment]
Looks insane!

**Pull request merged**
